project:
  type: website

website:
  title: "Saranjeet Kaur Bhogal"
  navbar:
    left:
      - text: "About"
        file: about.qmd
      - text: "Talks"
        file: talks/index.qmd
      - text: "Blogs"
        file: blogs/index.qmd

    right:
      - icon: github
        href: https://github.com/SaranjeetKaur
      - icon: linkedin
        href: https://www.linkedin.com/in/saranjeet-kaur-b-48ab769b/
      - icon: globe
        href: https://orcid.org/0000-0002-7038-1457
      - icon: envelope
        href: mailto:kaur.saranjeet3@gmail.com


format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

